/**
 * @project realistic-typewriter.js
 * @timestamp
 * @version 0.1
 * @author Fardjad
 * @description A pure Javascript library for simulating typewriter effect.
 Manually minified.
 */
function RealisticTypewriter(){"use strict";RealisticTypewriter.super_.call(this)}(function(){"use strict";function e(e){return e===e.toLowerCase()}function t(e,t){return Math.floor(Math.random()*(t-e+1)+e)}function n(r,i){var s,o,u,a,f,l;for(s=0;s<i.length;s++){for(o=0;o<i[s].length;o++){if(i[s][o].toLowerCase()===r){l=t(-1,1);a=s+l;if(a>=i.length||a<0){a+=-2*l}if(o>=i[a].length){o=i[a].length-1}if(l===0){l=[-1,1][t(0,1)]}else{l=t(-1,1)}u=o+l;if(u>=i[a].length||u<0){u+=-2*l}if(e(r)){f=i[a][u].toLowerCase()}else{f=i[a][u]}if(f===""){return n(r,i)}return f}}}return null}function r(e,r,i,s){var o=-1,u=false,a=-1;return{nextChar:function(){if(o>=e.length-1){if(a!==-1){u=true}else{return null}}if(!u){o++;u=a!==-1&&o%s===0;if(t(0,100)>i){var f=n(e.charAt(o),r);if(f===null){return e.charAt(o)}if(a===-1){a=o;u=t(0,1)===1}return f}return e.charAt(o)}if(o>=a){o--;return"\b"}u=false;a=-1;return e.charAt(++o)}}}RealisticTypewriter.super_=Object;RealisticTypewriter.prototype=Object.create(Object.prototype,{constructor:{value:RealisticTypewriter,enumerable:false},minimumCharactersPerSecond:{value:5,enumerable:false},maximumCharactersPerSecond:{value:15,enumerable:false},minimumInitialDelay:{value:500,enumerable:false},maximumInitialDelay:{value:1e3,enumerable:false},accuracy:{value:95,enumerable:false},keyboardLayout:{value:[["`","1","2","3","4","5","6","7","8","9","0","-","="],["","Q","W","E","R","T","Y","U","I","O","P","[","]","\\"],["","A","S","D","F","G","H","J","K","L",";","'"],["","Z","X","C","V","B","N","M",",",".","/"]],enumerable:false}});RealisticTypewriter.prototype.type=function(e,n,i){function a(e){var r=t(1e3/s.minimumCharactersPerSecond,1e3/s.maximumCharactersPerSecond),i=u();if(i===null){e(true);return}setTimeout(function(){if(i==="\b"){n.removeChild(n.lastChild)}else{var t=document.createElement("span");if(i===" "){t.innerHTML=" "}else{t.innerHTML=i}n.appendChild(t)}e(false)},r)}var s=this,o=(this.maximumCharactersPerSecond+this.minimumCharactersPerSecond)/2,u=r(e,this.keyboardLayout,this.accuracy,o).nextChar;if(e===undefined||e.length===0){return}if(n.removeChild===undefined||n.lastChild===undefined||n.appendChild===undefined){throw"Invalid DOMElement!"}if(document===undefined){throw"Can't find document object!"}setTimeout(function(){(function e(){a(function(t){if(t){if(i!==undefined&&typeof i==="function"){i()}return}setTimeout(e,0)})})()},t(s.minimumInitialDelay,s.maximumInitialDelay))}})()
